version: '3.8'
name: landing-coding-test

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/landing-coding-test
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: php-fpm
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/landing-coding-test
    depends_on:
      - mongodb

  mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - '27017:27017'
