controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

landing_page:
    path: /
    controller: App\Controller\LandingController::index